### ISSUE TITLE
NextJs + Phaser

### ISSUE THREAD

**Issue by khkmgch** [Recursion-Group-W/BombAttackers#18]
@hirotada-t @Hayato-Kossy 
NextJsでPhaserを試しているのですが、以下のコードで上手く動きません。
https://github.com/khkmgch/phaser-practice-3

Phaser使って上手くいった場合は教えてほしいです！

↓参考にした動画です。
https://www.youtube.com/watch?v=xRJ787usR5s

**Comment by khkmgch** [comment]
今日の夜から作業できるので再度試します。

**Comment by hirotada-t** [comment]
Phaserの実装部分ですよね？？
今は一番優先順位たかいですね。

見てみます。
夜は20:30頃から自習室にINしますねー

**Comment by hirotada-t** [comment]
とりあえずこのIssueのゴールとしては、昨日上げたゲームをNext仕様にして実装するところまでですかねー

**Comment by hirotada-t** [comment]
@khkmgch @Hayato-Kossy 
一応実装できました。
ただProblemがめちゃくちゃで手に負えないので、後ほど見てもらいたいです；；

取り急ぎ、僕のリポジトリにプッシュしてます。
後ほどPR送るので、そこでレビューして頂けると！
https://github.com/hirotada-t/next-phaser
