### ISSUE TITLE
feat:Characterクラスに残機パラメーターを追加する

### ISSUE THREAD

**Issue by hirotada-t** [Recursion-Group-W/BombAttackers#25]
現状のCharacterクラスに残機のパラメーターを持たせる。
プレイヤー残機の管理だけでなく、1回の爆発では倒せない敵を作る場合。

**Comment by khkmgch** [comment]
jeffryさんの要件定義にダメージアップがありました。
↓
「ダメージアップ：爆弾の威力が増える（初期値1, 最大値１０）」

残機だけ考えてたんですが、HPも必要ですかね？

**Comment by Hayato-Kossy** [comment]
僕は初級レベルを念頭に置いて作っているのでダメージアップは一回無視しました。

**Comment by khkmgch** [comment]
了解しました！
