### ISSUE TITLE
fix:画面が2つに増えるバグの修正

### ISSUE THREAD

**Issue by hirotada-t** [Recursion-Group-W/BombAttackers#28]

**Comment by khkmgch** [comment]
next.config.jsのreactStrictMode: false,にすると解決しました。

NextJsではなく、Reactの新機能によるものでした。
開発環境でライフサイクル内の問題を検出するために、レンダリングを2回行うという迷惑な機能がついてたみたいです。
本番環境には関係ないようです。
↓
https://ja.reactjs.org/docs/strict-mode.html

**Comment by hirotada-t** [comment]
ありがとうございます！

これ見て調べてみましたが、
「nextjs 2回　読み込み」
などで検索するとヒットしますね。

これは無視して進めますかー
