### ISSUE TITLE
feat:ストアでの状態管理

### ISSUE THREAD

**Issue by hirotada-t** [Recursion-Group-W/BombAttackers#29]

**Comment by khkmgch** [comment]
# 試すこと
- Phaser.Gameオブジェクトから現在のSceneにアクセス（シーンをkeyで探す、"Stage1"など）して、そこからプレイヤーを取り出す
- reactで作成したプレイヤークラスのインスタンスを、PhaserのSceneに渡して物理オブジェクトとして登録する
- Phaserの現在のScene自体をストアに登録してプレイヤーを取り出す

**Comment by khkmgch** [comment]
https://hopefourie.medium.com/successfully-integrating-phaser-3-into-your-react-redux-app-part-1-bade7feb460

**Comment by khkmgch** [comment]
Zustandの導入できたので、
設定画面からユーザーの入力（残機、キャラ選択、名前など）をもとにプレイヤーオブジェクトを作成してゲームが始められるようにします。
