### ISSUE TITLE
Phaserの参考文献

### ISSUE THREAD

**Issue by hirotada-t** [Recursion-Group-W/BombAttackers#35]
@khkmgch 
Kohさんが読んだPhaserの参考文献をシェア頂きたいです！

**Comment by khkmgch** [comment]
@hirotada-t  @Hayato-Kossy 

Qiitaにまとめればよかったですが、時間かかりそうなのでリンク貼ります。


### ドキュメントなど
① https://rexrainbow.github.io/phaser3-rex-notes/docs/site/
② https://photonstorm.github.io/phaser3-docs/index.html
※①でやりたいことを調べて、①のメソッドの名前やvscodeの型定義をもとに②で調べるみたいにやってます。

### Phaserのプロジェクト設定、マップの作成と読み込み
- https://qiita.com/gakuseikai/items/062d2c3d132bf430fcb9
- https://pablo.gg/en/blog/coding/how-to-create-a-top-down-rpg-maker-like-game-with-phaser-js-and-react/
- https://pablo.gg/en/blog/coding/i-made-a-top-down-game-version-of-my-blog-with-phaser-and-react/
- https://medium.com/swlh/grid-based-movement-in-a-top-down-2d-rpg-with-phaser-3-e3a3486eb2fd
- https://1-notes.com/phaser3-create-tile-map-with-tiled/
- https://mmorley.hatenablog.com/entry/2016/05/21/002430#%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%82%92%E8%BF%BD%E5%8A%A0
- https://qiita.com/raichi/items/5955f3e98f5ae995e57f
- https://pipoya.net/sozai/tips/tiled-tileset-edit/#%E3%82%BF%E3%82%A4%E3%83%AB%E3%83%BB%E3%83%AC%E3%82%A4%E3%83%A4%E3%83%BC%E3%81%AB%E3%82%88%E3%82%8B%E3%83%91%E3%83%BC%E3%83%84%E5%90%88%E6%88%90
- 

↓ マップを２次元配列で管理している例がありました。赤いレンガのタイルの番号を１みたいにしておけば、マップを動的に管理できそうです。
- https://magazine.halake.com/entry/phaser-ts-rpg-simple1

↓ 今使っているタイルの素材です。
- https://opengameart.org/content/20-sidescroller-tiles-by-starsteelgaming

### プレイヤー操作
- https://gentuki-blog.site/articles/6a9WWhxAZS4LVliXCzn6dL#%E3%82%AB%E3%83%BC%E3%82%BD%E3%83%AB%E3%82%AD%E3%83%BC%E3%82%92%E3%81%BE%E3%81%A8%E3%82%81%E3%81%A6%E7%99%BB%E9%8C%B2%E3%81%99%E3%82%8B---createcursorkeys()
- https://magazine.halake.com/entry/phaser-ts-rpg-simple2
- https://phasergames.com/how-to-flip-a-sprite-in-phaser-3/
- https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.Sprite.html#flipX__anchor
- https://photonstorm.github.io/phaser3-docs/Phaser.Input.Keyboard.html#.JustDown__anchor

### テキスト表示など
↓ この例のように、Phaser.GameObjects.Containerクラスを継承するテキストボックスのクラスを作成しておいて、それをPhaserのSceneにオブジェクトとして登録することで描画できるみたいです。
この感じでスコア表示やゲームオーバーのテキストなどカスタムできますね。
これを参考に、プレイヤーを作ってStoreで管理できそうです。
- https://qiita.com/non_cal/items/622108030aa2e516260c#5-%E3%83%80%E3%82%A4%E3%82%A2%E3%83%AD%E3%82%B0%E3%83%9C%E3%83%83%E3%82%AF%E3%82%B9%E3%81%AE%E4%BD%9C%E6%88%90

**Comment by hirotada-t** [comment]
いや～リンクシェアで十分です！
助かります😁

**Comment by hirotada-t** [comment]
こちらも参考に。

https://game-ac.com/tag/bomberman/

**Comment by khkmgch** [comment]
ありがとうございます！
たくさんありますね。対戦相手が強くて熱中してしまいました。
