### ISSUE TITLE
interfaceについて

### ISSUE THREAD

**Issue by khkmgch** [Recursion-Group-W/BombAttackers#40]
TypeScript始めたばかりで知らなかったのですが、interfaceやabstractクラス内ではpublicメソッドしか宣言できないみたいです。

javaみたいにprotectedとかprivateとか使えると思って、interfaceファイルを作ってたんですが、
interface使わない形で書き換えてみてもいいでしょうか？

**Comment by hirotada-t** [comment]
Javaもinterfaceでpublic以外の修飾子は使えないはず。
抽象クラスだと具象メソッドも書けるのでprotectedやprivateは使えた気がしますが、本来の目的とはちょっとズレる感じがしますね。
interfaceは具象メソッドがなくて継承が前提なので、publicでどこからでもアクセスできるようにしてるんだと思います。

privateにするとinterface内でしか使えないので、継承先から参照できなくなってしまいますし。
（protectedも許されていないのはちょっと謎）

もし間違ってたらすみません💦
このあたりは、OOPのポリモーフィズムについて書いてます。

**Comment by khkmgch** [comment]
@hirotada-t 

勘違いしてました！！ありがとうございます。

**Comment by khkmgch** [comment]
@hirotada-t 

勘違いしてました！！ありがとうございます。

よく考えたら、敵、障害物、ステージなどはinterface使ったほうが良いですね。
