### ISSUE TITLE
敵キャラ

### ISSUE THREAD

**Issue by khkmgch** [Recursion-Group-W/BombAttackers#9]
## 実装機能

![Monster drawio](https://user-images.githubusercontent.com/101968115/209159099-44294f08-f9b9-4639-83a1-07fd2d0e9e49.png)

キャラクラスから継承
- name:string
- id:number
- img:string
- coordinateX:number
- coordinateY:number
- speed:number
- isAttacked:bool

状態（怒ってる、サボってる、寝てる）
追跡アルゴリズム

setTimeoutで移動先の座標を補足し続ける。or requestAnimationFrameの再帰。
爆弾にヒットしたり、ゲームオーバー時に関数を止める。
- 一定のルートで動く
- 隣接する空きマスをランダムに選択
- プレイヤーとの距離が近づいたら捕捉

#### 変数
- name:string
- img:string
//位置(x, y)
- position: Position
//速度(x, y)
- velocity: Velocity
//気分(気分によって動きを変えるとか、、)
- mood: string

#### メソッド
- getName(): string
//位置(x, y)を取得
- getPosition(): Position
//速度(x, y)
- getVelocity(): Velocity
- getMood()

- 壁や障害物の有無によって先に進めるかどうか（衝突判定をする）（キャラクラスから継承？）
- 爆弾によってダメージを受けたかどうか判定する

- AIDecisionLevel1():number(マス目)→自分より左にいるか、右にいるか、上にいるか、下にいるかを判別し移動するAI。
- AIDecisionLevel2():number(マス目)→ダイクストラなど動的計画法アルゴリズムを再帰させ、移動するAI。
- ActivateAIDecision():void→条件によって上記のAIアルゴリズムを起動させるメソッド。
- playerAndAIManipulator():void→プレイヤーとAIの動作用のメソッド
- detectPlayerAttacked():void→敵もしくは爆弾がキャラクターに衝突した場合にキャラクタークラスに持たせたisAttackedをTrueにするメソッド。
- detectAIAttacked():void→爆弾が敵に衝突した場合にキャラクター(敵)クラスに持たせたisAttackedをTrueにするメソッド。
- destroyEnemy():void→キャラクター(敵)クラスに持たせたisAttackedがTrueのときidと合致した敵を破棄する。

### View
- 爆弾で倒された時の演出
## 【参考】
- アイディア
https://qiita.com/kh_kmgch/items/854b761ea3f0c7cb149a
- 要件
https://docs.google.com/document/d/18BGdX242Kfgy9QDSMDUBlxwCDL0T30Aw3RH6zjbwae0/edit

**Comment by hirotada-t** [comment]
現状のキャラクタークラスに残機のパラメーターを持たせておけば、1回の爆発では倒せない敵も作れますね。
